### ISSUE TITLE
I can't enable the mod

### ISSUE THREAD

**Issue by MoonLatte** [ProjectStarlight/StarlightRiver#156] opened 2022-02-14 08:31 UTC
Github issues should match the following format, for ease of organization and readability.

## Issue Description
	When I try to enable the mod on Tmodloader, it says there was an error, and all I can do is close the app.
## Reproduction
		Mod list: Starlight River
		Your inputs: Trying to enable, then reload the mod
		OS: Macbook pro
<img width="1434" alt="Screen Shot 2022-02-14 at 3 29 37 PM" src="https://user-images.githubusercontent.com/99642716/153827514-3369c453-90b8-4f46-ae5d-e37f10b53e66.png">

**Comment by ScalarVector1** [comment] 2022-04-18 16:34
duplicate of https://github.com/ProjectStarlight/StarlightRiver/issues/116

**Closed by ScalarVector1** 2022-04-18 16:34 UTC
Labels: duplicate, demo
