### ISSUE TITLE
Game crashing on seeing the vitric dessert biome.

### ISSUE THREAD

**Issue by cormon1** [ProjectStarlight/StarlightRiver#52] opened 2020-07-18 19:09 UTC

**Comment by cormon1** [comment] 2020-07-18 19:10
I tried 3 times, on 2 different worlds, and everytime the biome should start to be visible, the game stopped responding and i had to close it

**Comment by bobfishkins23** [comment] 2020-07-18 19:18
this issue is caused by the old smooth lighting coarseness setting being set to zero (you cant divide by zero :P), this feature is getting removed/replaced in the next build so im closing this for now.

**Closed by bobfishkins23** 2020-07-18 19:18 UTC
