### ISSUE TITLE
[Bug] Touchstone issue

### ISSUE THREAD

**Issue by Surwale** [ProjectStarlight/StarlightRiver#520] opened 2023-06-07 19:31 UTC
## Issue Description
The spirit that have to pop out of the touchstone in the ice biome doesen´t go anywhere
	The spirit only pops up in the same place.
	I found the same problem in all the touchstones.
![issue](https://github.com/ProjectStarlight/StarlightRiver/assets/135876093/b8037da7-6ed8-4ab6-b86a-2b301dd472f6)

**Comment by ScalarVector1** [comment] 2024-01-23 05:19
Closing due to lack of ability to reproduce

**Closed by ScalarVector1** 2024-01-23 05:19 UTC
Labels: Bug
