### ISSUE TITLE
datsuzei crashes if used with retro lighting on

### ISSUE THREAD

**Issue by Acefromreal** [ProjectStarlight/StarlightRiver#76] opened 2021-10-14 20:44 UTC
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: datsuzei spawning and going into my hand
	Actual behavior: game played the datsuzei sound before crashing
	Context: I recreated this several times, both in the ceiros fight and out
	Error message (if applicable): 
![image](https://user-images.githubusercontent.com/92549215/137390633-6c82e77d-ab15-4e80-b204-d91006c8e55d.png)

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: Starlight River, Yet Another Boss Health Bar, No More Tombs, Boss Checklist, Fargo's Mutant Mod, Magic Storage, Weaponout Lite, Smart Doors (from 1.4), Shorter Respawn Time, Recipe Browser, Omniswing, Luiafk, Calamity Mod Extra Music, AlchemistNPC Lite
		Config settings: 
![image](https://user-images.githubusercontent.com/92549215/137392003-c8732644-266a-4aae-96f9-7cbd4dd38361.png)

		Game settings: 
![image](https://user-images.githubusercontent.com/92549215/137392052-942035da-43cd-4ef7-aed3-9726b93c0a5e.png)
![image](https://user-images.githubusercontent.com/92549215/137392079-e037d227-5754-4dce-98b2-88ee6f4ae892.png)

		Gameplay events happening: replicated during ceiros and while chilling in the lobby
		Your inputs: double tapping down
		OS: windows 10

## Additional context and log files
**
[2021-07-30-41.zip](https://github.com/ProjectStarlight/StarlightRiver/files/7349258/2021-07-30-41.zip)
 ** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`

**Comment by ScalarVector1** [comment] 2021-10-18 03:53
Going to close this for now, for now the regular hotbar is not hidden on retro lighting modes. For now that is the intended behavior.

**Closed by ScalarVector1** 2021-10-18 03:53 UTC
Labels: bug, demo
