### ISSUE TITLE
[Bug] Failed to load asset: "Assets\Archaeology\NaturesGiftArtifact" while exploring jungle.

### ISSUE THREAD

**Issue by Snowbird334** [ProjectStarlight/StarlightRiver#503] opened 2023-06-06 16:46 UTC
Was walking through the jungle to the lefthand side of the world with the seed 3.1.1.River when the game printed an error message which read the following:

	Error message: ReLogic.Content.AssetLoadException: Asset could not be found: "Assets\Archaeology\NaturesGiftArtifact"
	  at ReLogic.Content.AssetRepository.LoadAssetWithPotentialAsync[T](Asset`1 asset, AssetRequestMode mode) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Content\AssetRepository.cs:line270

This error did not crash the game; closing the prompt and tabbing back in allowed further play.

The mod version 0.1.3 was installed via the #announcements channel on discord from this [message](https://discord.com/channels/616385262347485257/695000659862487041/1115495250362900550)
Mod list: only other mod was [Recipe Browser](https://steamcommunity.com/sharedfiles/filedetails/?id=2619954303) installed via steam.
OS: Windows 11

client.log attatched below
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11666899/client.log)

![image](https://github.com/ProjectStarlight/StarlightRiver/assets/135730644/1d2133e9-ad3e-4a4f-ab46-1636ed0748cb)

**Comment by ScalarVector1** [comment] 2024-01-23 05:21
Duplicate of fixed issue

**Closed by ScalarVector1** 2024-01-23 05:21 UTC
Labels: Bug
