### ISSUE TITLE
[Bug] Tentalance makes extremely high pitched noise and spawns a massive amount of dust when held.

### ISSUE THREAD

**Issue by CantWontDo** [ProjectStarlight/StarlightRiver#401] opened 2023-06-01 00:56 UTC
Github issues should match the following format, for ease of organization and readability.

## Issue Description
**A thorough description of the problem, including:**
	Expected behavior: Tentalance only makes dust when charging.
	Actual behavior: Tentalance makes a screeching noise when held and spawns lots of dust.

## Reproduction
**A detailed walkthrough of how to reproduce the issue, as thorough as possible.**
		Mod list: DragonLens, Starlight River
		Config settings: 
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/09cc7d44-ee6d-4dbf-a1b1-aea00e8c1dc8)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/a7f15547-ae70-4520-aa0c-e9bc00877f40)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/796dc6d2-8b11-4f2e-8bc1-a6b0d23840d8)

		Game settings:
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/8e9c8b14-b2c8-4767-83b1-bb91e00a23f1)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/4e8373f3-43d6-4e48-9f39-ec096f1c2318)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/b6ea0bbc-4233-4ec4-b572-c5d64cb3617c)
![image](https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/5f25c246-92ea-467b-aaf5-05d3ea6d47c6)

		Gameplay events happening: Holding tentalance.
		Your inputs: Hold tentalance.
		OS: Windows 10

## Additional context and log files
**Add any other context about the problem here.** 
Please attach Client.Log for all single-player issues and both Cleint.log and Server.log (if the host) for all multiplayer issues.
Log files are integral to identifying and fixing bugs and especially crashes. Please make sure you include the **ENTIRE LOG** and not just the final error message. Log files are usually found under `Documents\My Games\Terraria\ModLoader\Logs`
[Sound Warning]
https://github.com/ProjectStarlight/StarlightRiver/assets/78101150/b26979bb-6a7e-4427-ae20-af0bcf580e08
[client.log](https://github.com/ProjectStarlight/StarlightRiver/files/11619862/client.log)

**Comment by CantWontDo** [comment] 2023-06-01 00:59
This bug stopped happening after I talked to the bird npc.

**Comment by ScalarVector1** [comment] 2023-06-01 02:24
Cannot reproduce, please give more detailed reproduction steps

**Comment by Tourmalyn** [comment] 2023-06-04 14:36
I got the same bug, happens when you release the attack button at the exact moment the sound plays it seems. Persists even when putting it in a chest and closing it then taking it back out, only save exit fixes it. Here is a video Showcasing it. https://streamable.com/g2j02x

**Closed** 2023-07-07 17:16 UTC
Labels: bug
