### ISSUE TITLE
Auroracle doesn't despawn when the player dies

### ISSUE THREAD

**Issue by InvalidOS** [ProjectStarlight/StarlightRiver#11] opened 2021-05-22 22:49 UTC
self-explanatory

**Comment by TotallyNotAScalie** [comment] 2021-05-24 03:59
Can not reproduce -- can you provide any additional repo steps? Was your spawn point close enough to the arena it could have still registered you as in-range?

**Comment by InvalidOS** [comment] 2021-08-14 19:23
My spawnpoint wasn't anywhere close to the arena. It was the default spawnpoint.
The seed was "c4", large world, crimson.
I was also on Expert difficulty when this occurred.

**Comment by ScalarVector1** [comment] 2021-09-07 14:01
I have still been unable to reproduce this error. I am going to close this for now, if you can recreate this issue again reproducibly please reopen the issue.

**Closed by ScalarVector1** 2021-09-07 14:01 UTC
