### ISSUE TITLE
why I  can not use the mod in my MacBook

### ISSUE THREAD

**Issue by jkk752** [ProjectStarlight/StarlightRiver#125] opened 2021-11-10 11:45 UTC
[19:40:28] [1/INFO] [tML]: Starting tModLoader v0.11.8.5 OSX client (11/10/2021)
[19:40:28] [1/INFO] [tML]: Running on Mono 4.6.1
[19:40:28] [1/INFO] [tML]: Executable: /Users/ji/Library/Application Support/Steam/steamapps/common/tModLoader/tModLoader.app/Contents/MacOS/tModLoader.exe
[19:40:28] [1/INFO] [tML]: Working Directory: /Users/ji/Library/Application Support/Steam/steamapps/common/tModLoader/tModLoader.app/Contents/MacOS
[19:40:28] [1/INFO] [tML]: Launch Parameters: 
[19:40:28] [1/WARN] [tML]: First-chance exception reporting is not implemented on Mono
[19:40:28] [1/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null -> MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[19:40:28] [1/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[19:40:28] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.Utils, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[19:40:28] [1/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[19:40:28] [1/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[19:40:29] [1/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by Terraria
[19:40:30] [1/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[19:40:30] [1/INFO] [tML]: Checking Steam installation...
[19:40:30] [1/INFO] [tML]: Steam installation OK.
[19:40:30] [1/INFO] [Terraria]: Found Terraria steamapp install at: /Users/ji/Library/Application Support/Steam/steamapps/common/Terraria
[19:40:30] [1/INFO] [Terraria]: Steam Cloud Quota: 145.1 MB available
[19:40:32] [1/DEBUG] [Terraria]: Graphics Device: Color LCD {{Width:1440 Height:900 Format:Color}}
[19:40:37] [1/INFO] [Terraria]: Loaded 1000 vanilla assets
[19:40:42] [1/INFO] [Terraria]: Loaded 2000 vanilla assets
[19:40:46] [1/INFO] [Terraria]: Loaded 3000 vanilla assets
[19:40:51] [1/INFO] [Terraria]: Loaded 4000 vanilla assets
[19:40:56] [1/INFO] [Terraria]: Loaded 5000 vanilla assets
[19:41:03] [1/DEBUG] [tML]: Fallback synchronization context assigned
[19:41:06] [Threadpool worker/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[19:41:06] [Threadpool worker/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[19:41:07] [Threadpool worker/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null -> Mono.Cecil.Mdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[19:41:09] [Threadpool worker/INFO] [Terraria]: JIT loading finished
[19:41:09] [Threadpool worker/INFO] [tML]: Unloading mods
[19:41:10] [Threadpool worker/INFO] [tML]: 查找模组...
[19:41:10] [Threadpool worker/INFO] [tML]: 初始化...
[19:41:10] [Threadpool worker/INFO] [tML]: 初始化: ModLoader v0.11.8.5
[19:41:12] [Threadpool worker/INFO] [tML]: 安装中...
[19:41:12] [Threadpool worker/INFO] [tML]: 加载中: ModLoader v0.11.8.5
[19:41:12] [Threadpool worker/INFO] [tML]: RAM usage: 833.9 MB
[19:41:12] [Threadpool worker/INFO] [tML]: 添加合成配方...
[19:41:36] [1/INFO] [tML]: Enabling Mod: StarlightRiver
[19:41:37] [Threadpool worker/INFO] [tML]: Unloading mods
[19:41:37] [Threadpool worker/INFO] [tML]: 卸载中: tModLoader
[19:41:38] [Threadpool worker/INFO] [tML]: 查找模组...
[19:41:38] [Threadpool worker/INFO] [tML]: 增容中: StarlightRiver
[19:41:38] [Threadpool worker/INFO] [tML]: 初始化...
[19:41:38] [Threadpool worker/DEBUG] [tML]: Assembly Resolve: StarlightRiver_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
[19:41:38] [Threadpool worker/INFO] [tML]: 初始化: ModLoader v0.11.8.5
[19:41:41] [Threadpool worker/INFO] [tML]: 初始化: StarlightRiver v0.1
[19:41:52] [Threadpool worker/DEBUG] [tML]: Assembly Resolve: StarlightRiver_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[19:41:52] [Threadpool worker/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> Terraria, Version=1.3.5.1, Culture=neutral, PublicKeyToken=null
[19:41:52] [Threadpool worker/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[19:41:52] [Threadpool worker/WARN] [tML]: Upgraded Reference MonoMod.RuntimeDetour -> Version=19.12.19.1 -> 20.11.16.1
[19:41:52] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::PickTile(int, int, int) added by StarlightRiver_0
[19:41:52] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.WorldGen::PlaceTile(int, int, int, bool, bool, int, int) added by StarlightRiver_0
[19:41:52] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::KeyDoubleTap(int) added by StarlightRiver_0
[19:41:52] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawInterface_Resources_Mana() added by StarlightRiver_0
[19:41:52] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::HealEffect(int, bool) added by StarlightRiver_0
[19:41:52] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawPlayer(Player, Vector2, float, Vector2, float) added by StarlightRiver_0
[19:41:53] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawInterface_30_Hotbar() added by StarlightRiver_0
[19:41:53] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::KeyDoubleTap(int) added by StarlightRiver_0
[19:41:53] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::MouseText_DrawItemTooltip(int, byte, int, int) added by StarlightRiver_0
[19:41:53] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::KeyDoubleTap(int) added by StarlightRiver_0
[19:41:53] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::PickTile(int, int, int) added by StarlightRiver_0
[19:41:53] [Threadpool worker/WARN] [tML]: Granted native detouring access to StarlightRiver_0
[19:41:53] [Threadpool worker/DEBUG] [tML]: Hook Terraria.ModLoader.PlayerHooks::UpdateBadLifeRegen(Player) -> StarlightRiver.Core.DoTResistancePlayer::ReduceDoT(Action`1, Player) by StarlightRiver_0
[19:41:53] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.WorldGen::meteor(int, int) added by StarlightRiver_0
[19:41:53] [Threadpool worker/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[19:41:53] [Threadpool worker/WARN] [tML]: Upgraded Reference MonoMod.Utils -> Version=19.12.19.1 -> 20.11.16.1
[19:41:53] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawTiles(bool, int) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::InitTargets(int, int) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::AddLight(int, int, float, float, float) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::LightTiles(int, int, int, int) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::PreRenderPhase() modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::PreRenderPhase() modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::Brightness(int, int) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::GetBlackness(int, int) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::GetColor(int, int) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::GetColor(int, int, Color) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::GetColor4Slice(int, int, ref Color[]) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::GetColor4Slice_New(int, int, out VertexColors, Color, float) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::GetColor4Slice_New(int, int, out VertexColors, float) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::GetColor9Slice(int, int, ref Color[]) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::Initialize(bool) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::doColors() modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawBlack(bool) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawWalls() modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::drawWaters(bool, int, bool) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Lighting::PreRenderPhase() added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Lighting::LightTiles(int, int, int, int) added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.IO.WorldFile::SaveWorldTiles(BinaryWriter) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.IO.WorldFile::LoadWorldTiles(BinaryReader, Boolean[]) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Tile::isTheSameAs(Tile) added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::CheckMonoliths() added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.GameContent.UI.Elements.UIWorldListItem::DrawSelf(SpriteBatch) added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.GameContent.UI.Elements.UIWorldListItem::.ctor(WorldFileData, int) added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.GameContent.UI.States.UIWorldSelect::.ctor() added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::dropItemCheck() added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::LeftClick(Item[], int, int) added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::Draw(SpriteBatch, Item[], int, int, Vector2, Color) added by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Player::ScrollHotbar(int) modified by StarlightRiver_0
[19:41:54] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by StarlightRiver_0
[19:41:55] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Item::Prefix(int) modified by StarlightRiver_0
[19:41:55] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawInterface_Resources_Life() modified by StarlightRiver_0
[19:41:55] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.NPC::GetChat() added by StarlightRiver_0
[19:41:55] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::SpawnTownNPC(int, int) modified by StarlightRiver_0
[19:41:55] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.NPC::checkDead() modified by StarlightRiver_0
[19:41:55] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawInventory() modified by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::LeftClick(Item[], int, int) added by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::Draw(SpriteBatch, Item[], int, int, Vector2, Color) added by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::RightClick(Item[], int, int) added by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawDust() added by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.GameContent.UI.Elements.UICharacterListItem::DrawSelf(SpriteBatch) added by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.GameContent.UI.Elements.UICharacterListItem::.ctor(PlayerFileData, int) added by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.GameContent.Liquid.LiquidRenderer::InternalDraw(SpriteBatch, Vector2, int, float, bool) modified by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawTiles(bool, int) modified by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.GameContent.Liquid.LiquidRenderer::InternalPrepareDraw(Rectangle) modified by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawUnderworldBackground(bool) added by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::CheckMonoliths() added by StarlightRiver_0
[19:41:56] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DoDraw(GameTime) modified by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawInterface(GameTime) added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawProjectiles() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::CheckMonoliths() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::drawWaters(bool, int, bool) added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawItems() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawPlayer(Player, Vector2, float, Vector2, float) added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Projectile::Update(int) added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawInterface_27_Inventory() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Graphics.SpriteViewMatrix::ShouldRebuild() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawMap() modified by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawInfernoRings() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawDust() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.WorldGen::SaveAndQuit(Action) added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::CheckMonoliths() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawBackgroundBlackFill() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawBlack(bool) added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawBlack(bool) modified by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Lighting::PreRenderPhase() modified by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::CheckMonoliths() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawDust() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::Update_NPCCollision() added by StarlightRiver_0
[19:41:57] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Projectile::VanillaAI() modified by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawMap() modified by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::DropSelectedItem() added by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::dropItemCheck() added by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::ItemFitsItemFrame(Item) added by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Player::ItemFitsWeaponRack(Item) added by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawInterface_20_MultiplayerPlayerNames() added by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawInterface_14_EntityHealthBars() added by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawPlayer_DrawAllLayers(Player, int, int) modified by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawPlayer(Player, Vector2, float, Vector2, float) added by StarlightRiver_0
[19:42:01] [Threadpool worker/DEBUG] [tML]: Hook IL.Terraria.Main::DoDraw(GameTime) modified by StarlightRiver_0
[19:42:01] [Threadpool worker/ERROR] [tML]: 该模组加载时发生错误 StarlightRiver
该模组已被自动禁用.
System.InvalidProgramException: Invalid IL code in (wrapper dynamic-method) Terraria.Main:DMD<Terraria.Main::DoDraw> (Terraria.Main,Microsoft.Xna.Framework.GameTime): IL_4025: ldfld     0x00000da5

  at (wrapper managed-to-native) System.RuntimeMethodHandle:GetFunctionPointer (intptr)
  at System.RuntimeMethodHandle.GetFunctionPointer () [0x00000] in mscorlib.dll 
  at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetFunctionPointer (MethodBase method, RuntimeMethodHandle handle) [0x00000] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetNativeStart (MethodBase method) [0x0002f] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.DetourHelper.GetNativeStart (MethodBase method) [0x00005] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.Detour._TopApply () [0x00015] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.Detour._RefreshChain (MethodBase method) [0x00113] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.Detour.Apply () [0x00053] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.Detour..ctor (MethodBase from, MethodBase to, DetourConfig& config) [0x002cc] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.ILHook+Context.Refresh () [0x0012d] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.ILHook.Apply () [0x00059] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.ILHook..ctor (MethodBase from, Manipulator manipulator, ILHookConfig& config) [0x00152] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.ILHook..ctor (MethodBase from, Manipulator manipulator, ILHookConfig config) [0x00000] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.ILHook..ctor (MethodBase from, Manipulator manipulator) [0x0001c] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewILHook (MethodBase from, Manipulator to) [0x00000] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate] (Func[T1,T2,TResult] gen, TDelegate hookDelegate) [0x0003c] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify (Delegate hookDelegate) [0x00013] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify (MethodBase method, Delegate callback) [0x00028] in data-0x112b0f000 
  at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify[T] (MethodBase method, Delegate callback) [0x00000] in data-0x112b0f000 
  at IL.Terraria.Main.add_DoDraw (Manipulator ) [0x0000a] in data-0x174f11000 
  at StarlightRiver.Content.CustomHooks.WaterAddonHandler.Load () in StarlightRiver\Content\CustomHooks\Visuals.WaterAddonHandler.cs:56 
  at StarlightRiver.StarlightRiver.Load () in StarlightRiver.cs:100 
  at Terraria.ModLoader.ModContent+<>c.<Load>b__38_0 (Mod mod) [0x0001f] in tModLoader.exe 
  at Terraria.ModLoader.ModContent.LoadModContent (CancellationToken token, Action[T] loadAction) [0x00047] in tModLoader.exe 
[19:42:01] [Threadpool worker/INFO] [tML]: Disabling Mod: StarlightRiver
[19:43:52] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "/Users/ji/Library/Application Support/Terraria/ModLoader/Logs/client.log" 
[19:43:53] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "/Users/ji/Library/Application Support/Terraria/ModLoader/Logs/client.log" 
[19:43:55] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "/Users/ji/Library/Application Support/Terraria/ModLoader/Logs/client.log"

**Comment by ScalarVector1** [comment] 2021-11-10 15:53
does not follow the correct format and is a duplicate of https://github.com/ProjectStarlight/StarlightRiver/issues/116 .

**Closed by ScalarVector1** 2021-11-10 15:53 UTC
Labels: duplicate, demo
